# -*- coding: utf-8 -*-
"""Sentiment Analysis on Movie Reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nc1RCGvOrgtQr9_DTRCSU0TiOF0vIxC
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt

data = {
    'review': [
        'This movie was absolutely amazing! I loved every minute of it.',
        'Terrible film, waste of time and money. Fell asleep halfway.',
        'Great acting, compelling storyline. Highly recommend!',
        'Boring and predictable. Expected much better from this director.',
        'One of the best movies I have seen this year. Outstanding!',
        'Awful script and poor cinematography. Very disappointed.',
        'Excellent film with great character development.',
        'Worst movie ever made. Do not watch.',
        'Simply brilliant and inspiring. A masterpiece.',
        'Not worth watching. Slow paced and dull.',
        'Fantastic performance by the lead actor!',
        'Disappointing and confusing plot. Lost interest quickly.',
        'Loved it! Perfect mix of action and drama.',
        'Boring dialogue and weak plot. Not recommended.',
        'Amazing cinematography and soundtrack. A true gem!',
        'Horrible acting. Could not finish watching it.',
        'Wonderful storytelling and beautiful visuals.',
        'Waste of money. Plot made no sense.',
        'Exceptional movie! Will watch again.',
        'Dreadful. One of the worst films I have ever seen.'
    ],
    'sentiment': [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
}

df = pd.DataFrame(data)
print(f"Dataset shape: {df.shape}")
print(f"Sentiment distribution:\n{df['sentiment'].value_counts()}")
print("\nFirst few reviews:")
print(df.head())

vectorizer = TfidfVectorizer(max_features=100, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(df['review'])
y = df['sentiment']

print(f"Feature matrix shape: {X.shape}")
print(f"Number of features extracted: {len(vectorizer.get_feature_names_out())}")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=10)
model.fit(X_train, y_train)

print(f"Training set size: {X_train.shape[0]}")
print(f"Test set size: {X_test.shape[0]}")
print("Model training completed!")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Model Performance Metrics:")
print(f"Accuracy:  {accuracy:.2%}")
print(f"Precision: {precision:.2%}")
print(f"Recall:    {recall:.2%}")
print(f"F1-Score:  {f1:.2%}")

feature_names = vectorizer.get_feature_names_out()
importances = model.feature_importances_
top_indices = np.argsort(importances)[-10:]

print("\nTop 10 Most Important Features:")
for idx in reversed(top_indices):
    print(f"  {feature_names[idx]}: {importances[idx]:.4f}")

test_reviews = [
    "This film was fantastic and engaging!",
    "Absolutely horrible, terrible waste of time."
]

test_vectors = vectorizer.transform(test_reviews)
predictions = model.predict(test_vectors)
confidence = model.predict_proba(test_vectors)

print("\nPredictions on New Reviews:")
for review, pred, conf in zip(test_reviews, predictions, confidence):
    sentiment = "Positive" if pred == 1 else "Negative"
    print(f"Review: {review}")
    print(f"Prediction: {sentiment} (Confidence: {conf[pred]:.2%})\n")

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
plt.title('Confusion Matrix - Sentiment Classification')
plt.colorbar()
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.xticks([0, 1], ['Negative', 'Positive'])
plt.yticks([0, 1], ['Negative', 'Positive'])
for i in range(2):
    for j in range(2):
        plt.text(j, i, str(cm[i, j]), ha='center', va='center', color='white' if cm[i, j] > cm.max()/2 else 'black')
plt.tight_layout()
plt.show()